services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    restart: always
    environment:
      ORACLE_PASSWORD: devtrack123
      APP_USER: devtrack
      APP_USER_PASSWORD: devtrack123
      ORACLE_DATABASE: XEPDB1
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devtrack-api
    restart: always
    depends_on:
      - oracle
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__OracleDb: Data Source=oracle:1521/XEPDB1;User Id=devtrack;Password=devtrack123;
      Jwt__Secret: ReplaceThisWithASecure32CharOrLongerSecret!
      Jwt__Issuer: DevTrackAI
      Jwt__Audience: DevTrackAI.Client
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devtrack-frontend
    restart: always
    depends_on:
      - api
    ports:
      - "4200:4200"

volumes:
  oracle_data:
